name: Access variables on linux
on:
  push:


jobs:
  bash:
    name: Access variable on bash
    runs-on: ubuntu-latest
    steps:
    - name: Print all environment variable
      run: |
        env
    
    - name: Default Environment Variables that github set
      run: |
        echo $GITHUB_WORKSPACE

    - name: Defining environment variables for a workflow using env keyword
      run: |
        echo $Greeting
      env:
        Greeting: Hello
    
    - name: Create and access global environment variable for linux (bash)
      run: |
        export variable1="valueExport" 
        echo $variable1
 
    - name: Use environment variable set in above step
      run: |
        if [[ $variable1 == "" ]]; then
          echo "false"
        fi

    - name: Generate value in one step and use it in other step (GITHUB_ENV)
      run: |
        echo "action_state=yellow" >> "$GITHUB_ENV"
        echo $action_state 

    - name: Use variable generated in above step
      run: |
        if [[ $action_state == "" ]]; then
          echo "false"
        fi
        
    - name: Is the above variable set as a environment variable?
      run: |
        env		  

    - name: Access Already set environment variable on runner
      run: |
        echo $JAVA_HOME

    - name: Storing and access shell variable for a step
      run: |
        VERSION=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)
        echo $VERSION
    
    - name: Is the above variable set a environment variable?
      run: |	  
        if [[ $VERSION == "" ]]; then
          echo "false"
        fi