name: Access variables on windows
on:
  push:


jobs:
  cmd:
    name: Access variable on cmd
    runs-on: self-hosted
    steps:
    - name: Print all environment variable
      run: |
        set
      shell: cmd
    
    - name: Default Environment Variables that github set
      run: |
        echo %GITHUB_WORKSPACE%
      shell: cmd

    - name: Defining environment variables for a workflow using env keyword
      run: |
        echo %Greeting%
      env:
        Greeting: Hello
      shell: cmd
    
    - name: Create and access global environment variable for windows (cmd)
      run: |
        set variable1="valueExport" 
        echo %variable1%
      shell: cmd
 
    - name: Use environment variable set in above step
      run: |
        IF "%variable1%"==""  (
        echo "false"
        )        
      shell: cmd

    - name: Generate value in one step and use it in other step (using GITHUB_ENV)
      run: |
        echo "action_state=yellow" >> "$GITHUB_ENV"
        echo %action_state% 
      shell: cmd

    - name: Use variable generated in above step
      run: |
        IF "%action_state%"=="" (   
        echo "false"  
        )        
      shell: cmd
        
    - name: Is the above variable set as a environment variable?
      run: |
        set
      shell: cmd  

    - name: Access Already set environment variable on runner
      run: |
        echo %MAVEN_HOME%
      shell: cmd

    - name: Store and access shell variable for a step
      run: |
        set VERSION=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)
        echo %VERSION%
      shell: cmd
    
    - name: Is the above variable set a environment variable?
      run: |	  
        IF "%VERSION%"=="" (
        echo "false"
        )
      shell: cmd