name: Access variables on windows
on:
  push:


jobs:
  powershell:
    name: Access variable on windows
    runs-on: self-hosted
    steps:
    - name: Print all environment variable
      run: |
        ls env:
    
    - name: Default Environment Variables that github set
      run: |
        echo $env:GITHUB_WORKSPACE

    - name: Defining environment variables for a workflow using env keyword
      run: |
        echo $env:Greeting
      env:
        Greeting: Hello
    
    - name: Create and access global environment variable for linux (bash)
      run: |
        $env:variable1="valueExport" 
        echo $env:variable1
 
    - name: Use environment variable set in above step
      run: |
        if($env:variable1 -eq "") {
          echo "false"
        }

    - name: Generate value in one step and use it in other step (GITHUB_ENV)
      run: |
        echo "action_state=yellow" >> "$GITHUB_ENV"
        echo $env:action_state 

    - name: Use variable set in above step
      run: |
        if($env:action_state -eq "") {
          echo "false"
        }
        
    - name: Is the above variable set a environment variable?
      run: |
        ls env:		  

    - name: Access Already set environment variable on runner
      run: |
        echo $env:MAVEN_HOME

    - name: Storing and access shell variable for a step
      run: |
        $VERSION=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)
        echo $env:VERSION
    
    - name: Is the above variable set a environment variable?
      run: |	  
        if($env:VERSION -eq "") {
          echo "false"
        }